version: "3"

services:
  nginx:
    container_name: nginx-next
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3001:80
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
