version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 3001:80
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    user: node
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
